### ISSUE TITLE
KeyError: 'items' when trying to create GCE keypair

### ISSUE THREAD

**Issue by machristie** [gvlproject/cloudbridge#46]
Getting an error when following the CloudBridge tutorial at the part where I try to create a keypair:

```
>>> from cloudbridge.cloud.factory import CloudProviderFactory, ProviderList
>>> config = {
...     'gce_client_email': '795623318794-compute@developer.gserviceaccount.com',
...     'gce_project_name': 'cloudlaunch-169515',
...     'gce_service_creds_file': './CloudLaunch-d9757cca220c.json',
...     'gce_default_zone': 'us-central1-a',
...     'gce_region_name': 'us-central1',
... }
>>> provider = CloudProviderFactory().create_provider(ProviderList.GCE, config)
[aws provider] moto library not available!
>>> kp = provider.security.key_pairs.create('cloudbridge_intro')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/machrist/SGCI/cloudlaunch/cloudbridge/cloudbridge/cloudbridge/cloud/providers/gce/services.py", line 185, in create
    kp = self.find(name=name)
  File "/Users/machrist/SGCI/cloudlaunch/cloudbridge/cloudbridge/cloudbridge/cloud/providers/gce/services.py", line 178, in find
    for kp in self.list():
  File "/Users/machrist/SGCI/cloudlaunch/cloudbridge/cloudbridge/cloudbridge/cloud/providers/gce/services.py", line 166, in list
    for gce_kp in self._iter_gce_key_pairs():
  File "/Users/machrist/SGCI/cloudlaunch/cloudbridge/cloudbridge/cloudbridge/cloud/providers/gce/services.py", line 85, in _iter_gce_key_pairs
    for kpinfo in self._iter_gce_ssh_keys(metadata):
  File "/Users/machrist/SGCI/cloudlaunch/cloudbridge/cloudbridge/cloudbridge/cloud/providers/gce/services.py", line 117, in _iter_gce_ssh_keys
    sshkeys = self._get_or_add_sshkey_entry(metadata)["value"]
  File "/Users/machrist/SGCI/cloudlaunch/cloudbridge/cloudbridge/cloudbridge/cloud/providers/gce/services.py", line 102, in _get_or_add_sshkey_entry
    entries = [item for item in metadata["items"]
KeyError: 'items'
```

I can successfully list compute images and instance types so I know my setup works.

@afgane @nuwang @mbookman

**Comment by nuwang** [comment]
@machristie This has been fixed in: https://github.com/gvlproject/cloudbridge/pull/33
It's awaiting review.

**Comment by nuwang** [comment]
Fix merged.
